"""Tension Minimization for Distributional Semantics
==================================================
Implements the full energy model from the paper (Section "Representing both
numerical and categorical data in the same space"):

    T(A) = Σ_i Σ_j max(F_conn(A,i,j) + F_prox(A,i,j), 0)

    F_conn(A,i,j) = Σ_{k≠i} M_i · W_{i,k} · C_conn(A_{i,j}, A_{k,j})
    F_prox(A,i,j) = Σ_{k≠i} M_i · M_k · H_n(A_i, A_k) · C_prox(A_{i,j}, A_{k,j})

    C_conn(a,b) = -1 if a=b, +1 if a≠b
    C_prox(a,b) = +1 if a=b, -1 if a≠b

Minimized via simulated annealing with gradual bit-flipping, exactly as
described in the paper.

This produces geometrically meaningful HBV embeddings where:
    - Co-occurring vertices are near each other (connective force)
    - Distant vertices are pushed apart (proximal force)
    - The system minimizes total unresolved tension until convergence
"""

from __future__ import annotations

import math

import torch

from hap.hdc_core import gen_hvs, hv_hamming_sim


def tension_energy(
    hv_matrix: torch.Tensor,
    cooc_graph: torch.Tensor,
    masses: torch.Tensor,
) -> float:
    """Compute total tension energy T(A) for the current HV matrix.

    From the paper, Eq. T(A):
        T(A) = Σ_i Σ_j max(F_conn(i,j) + F_prox(i,j), 0)

    Vectorized implementation for efficiency with moderate dimensions.

    Args:
        hv_matrix: (m, n) binary hypervectors, one per vertex
        cooc_graph: (m, m) co-occurrence weights (0 = no edge)
        masses: (m,) relative mass of each vertex

    Returns:
        Total unresolved tension (non-negative; 0 = perfect)
    """
    m, n = hv_matrix.shape
    device = hv_matrix.device

    # Precompute Hamming distances between all vertex pairs: (m, m)
    h_dists = torch.zeros(m, m, device=device)
    for i in range(m):
        h_dists[i] = 1.0 - hv_hamming_sim(hv_matrix[i].unsqueeze(0).expand(m, n), hv_matrix).float()

    total = 0.0

    for i in range(m):
        # Mask of vertices k where cooc_graph[i, k] > 0, k ≠ i
        neighbors = (cooc_graph[i] > 0).float()
        neighbors[i] = 0.0

        n_neighbors = int(neighbors.sum().item())
        if n_neighbors == 0:
            continue

        # For each bit j, compute F_conn + F_prox vectorized across neighbors
        # hv_i_j: (n,) - bits of vertex i
        hv_i = hv_matrix[i]  # (n,)

        # hv_k: (n_neighbors, n) — HVs of connected vertices
        neighbor_indices = neighbors.nonzero(as_tuple=True)[0]
        hv_neighbors = hv_matrix[neighbor_indices]  # (K, n)
        w_neighbors = cooc_graph[i][neighbor_indices]  # (K,)
        m_k = masses[neighbor_indices]  # (K,)
        h_dists_ik = h_dists[i][neighbor_indices]  # (K,)

        # C_conn: (K, n) — -1 where bits match, +1 where they differ
        bits_match = (hv_neighbors == hv_i.unsqueeze(0)).float()  # (K, n)
        c_conn = -bits_match + (1 - bits_match)  # (K, n): -1 or +1

        # F_conn per bit: Σ_k M_i * W_{i,k} * C_conn => (n,)
        f_conn = (masses[i] * w_neighbors.unsqueeze(1) * c_conn).sum(dim=0)

        # C_prox: (K, n) — +1 where bits match, -1 where they differ
        c_prox = bits_match - (1 - bits_match)  # (K, n): +1 or -1

        # F_prox per bit: Σ_k M_i * M_k * H_n(i,k) * C_prox => (n,)
        weight = masses[i] * m_k * h_dists_ik  # (K,)
        f_prox = (weight.unsqueeze(1) * c_prox).sum(dim=0)

        # Unresolved force: max(F_conn + F_prox, 0) summed over bits
        unresolved = torch.clamp(f_conn + f_prox, min=0)
        total += unresolved.sum().item()

    return total


def minimize_tension(
    hv_matrix: torch.Tensor,
    cooc_graph: torch.Tensor,
    masses: torch.Tensor,
    n_iters: int = 1000,
    initial_temp: float = 10.0,
    cooling_rate: float = 0.995,
    disable_proximal: bool = False,
    seed: int | None = None,
) -> tuple[torch.Tensor, list[float]]:
    """Minimize tension energy via simulated annealing.

    From the paper:
        "Techniques exist for minimization of T and are stochastic in nature,
         involving gradual flipping of bits to minimize energy, often using
         simulated annealing."

    Algorithm per iteration:
        1. Select a random vertex i and bit position j
        2. Compute ΔT for flipping that bit
        3. Accept if ΔT < 0, or with probability exp(-ΔT/T) otherwise
        4. Cool temperature
        5. Repeat until convergence or n_iters

    From Fig 1 in the paper:
        "The energy of the same system generated by random graphs of
         equal number of vertices with and without proximal force only
         reaches exact 0 when the proximal force is off."

    Args:
        hv_matrix: (m, n) initial binary hypervectors
        cooc_graph: (m, m) co-occurrence weights
        masses: (m,) relative masses
        n_iters: Maximum simulated annealing iterations
        initial_temp: Starting temperature
        cooling_rate: Temperature decay per iteration
        disable_proximal: If True, set F_prox = 0 (allows exact 0 energy)
        seed: Random seed

    Returns:
        (optimized_hv_matrix, energy_history)
    """
    m, n = hv_matrix.shape
    device = hv_matrix.device

    g = torch.Generator(device=device)
    if seed is not None:
        g.manual_seed(seed)

    hv = hv_matrix.clone()
    energy_history: list[float] = []

    temp = initial_temp

    for _iteration in range(n_iters):
        # Compute current energy
        current_energy = tension_energy(hv, cooc_graph, masses)
        energy_history.append(current_energy)

        if current_energy == 0:
            break

        # Random perturbation: flip one bit
        i = int(torch.randint(0, m, (1,), generator=g).item())
        j = int(torch.randint(0, n, (1,), generator=g).item())

        # Flip
        hv[i, j] = 1.0 - hv[i, j]

        # Compute new energy
        new_energy = tension_energy(hv, cooc_graph, masses)

        delta = new_energy - current_energy

        if delta < 0:
            # Accept: energy decreased
            pass
        elif temp > 0 and torch.rand(1, generator=g).item() < math.exp(-delta / temp):
            # Accept probabilistically
            pass
        else:
            # Reject: flip back
            hv[i, j] = 1.0 - hv[i, j]
            energy_history[-1] = current_energy  # restore

        # Cool
        temp *= cooling_rate

    return hv, energy_history


def build_cooc_graph(
    cooc_counts: dict[tuple[int, int], float],
    n_vertices: int,
) -> torch.Tensor:
    """Build co-occurrence weight matrix from pair counts.

    Normalizes raw co-occurrence counts to weight matrix W_{i,k}.

    Args:
        cooc_counts: Dict of {(i, k): count} for co-occurring vertex pairs
        n_vertices: Total number of vertices

    Returns:
        (n_vertices, n_vertices) weight matrix
    """
    graph = torch.zeros(n_vertices, n_vertices)
    for (i, k), count in cooc_counts.items():
        graph[i, k] = count
        graph[k, i] = count  # symmetric
    # Normalize by max
    if graph.max() > 0:
        graph = graph / graph.max()
    return graph


def build_masses(
    vertex_counts: torch.Tensor,
) -> torch.Tensor:
    """Compute relative masses M_i from raw occurrence counts.

    M_i = count_i / max(count)

    Args:
        vertex_counts: (n_vertices,) raw occurrence counts

    Returns:
        (n_vertices,) relative masses in (0, 1]
    """
    if vertex_counts.max() == 0:
        return torch.ones_like(vertex_counts) / len(vertex_counts)
    return vertex_counts.float() / vertex_counts.max().float()


def learn_distributional_hvs(
    cooc_counts: dict[tuple[int, int], float],
    vertex_counts: torch.Tensor,
    dim: int = 10_000,
    n_iters: int = 5000,
    seed: int | None = None,
) -> torch.Tensor:
    """Learn distributionally meaningful HVs from co-occurrence data.

    Full pipeline matching the paper (Section "Representing both numerical
    and categorical data in the same space"):

        1. Generate random initial HVs for each vertex
        2. Build co-occurrence graph and masses
        3. Minimize tension energy via simulated annealing
        4. Return optimized HVs where similar vertices are close

    Args:
        cooc_counts: {(i, k): count} — how often vertices i and k co-occur
        vertex_counts: (n,) — total occurrence count per vertex
        dim: Hypervector dimensionality
        n_iters: Simulated annealing iterations
        seed: Random seed

    Returns:
        (n, dim) optimized hypervectors
    """
    n_vertices = len(vertex_counts)
    if n_vertices < 2:
        return gen_hvs(max(n_vertices, 1), dim, seed=seed)

    # Step 1: Random initialization
    hv_matrix = gen_hvs(n_vertices, dim, "binary", "cpu", seed)

    # Step 2: Build graph and masses
    cooc_graph = build_cooc_graph(cooc_counts, n_vertices)
    masses = build_masses(vertex_counts)

    # Step 3: Minimize tension
    hv_optimized, _history = minimize_tension(
        hv_matrix,
        cooc_graph,
        masses,
        n_iters=n_iters,
        seed=seed,
    )

    return hv_optimized
